# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
encoding: utf-8
# Site settings
title: Conge
brief-intro: 精进
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://conge.github.io' # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: conge
facebook_username: psychattic
github_username: conge
email: congel@gmail.com
weibo_username:
zhihu_username:
linkedIn_username: qingyang-li
dribbble_username:

description_footer: 脚踏实地

# comments
# 四种评论插件，选一个就好了。
# 推荐国内使用Waline， before use it you need to setit up to get serverURL
# https://waline.js.org/guide/get-started.html
disqus_shortname: #lework
gitalk:
  enable: #false
  clientID: #
  clientSecret: #
  repo: #conge.github.io
  owner: #conge
  admin: #conge
utteranc_es:
  enable: #true
  repo: 'conge/conge.github.io'
  issue-term: title
  theme: github-light
Valine:
  enable:
  appId:
  appKey:
  serverURLs: https://xxxx.api.lncldglobal.com
  placeholder:
Waline:
  enable: true
  serverURL: https://waline.livingwithfcs.org/

# 赞赏
reward:
  enable: true
  wechat: /assets/images/WechatIMG26.jpeg
  alipay: #/assets/images/reward/alipay.png

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id:
google_analytics_id: G-W3B8S6L83W

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 10

exclude: [ "LICENSE", ".post-template", ".gitignore", "start.bat"]
